// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by Rivet Code Generator
// Generated at: 2025-11-25 10:54:26.671469

import 'dart:convert';
import 'package:http/http.dart' as http;

/// Auto-generated API client for your Rivet backend
///
/// Usage:
/// ```dart
/// final client = RivetClient('http://localhost:3000');
/// final result = await client.get('/endpoint');
/// ```
class RivetClient {
  final String baseUrl;
  final http.Client _client;
  final Map<String, String> _defaultHeaders;

  RivetClient(
    this.baseUrl, {
    http.Client? client,
    Map<String, String>? defaultHeaders,
  }) : _client = client ?? http.Client(),
       _defaultHeaders = defaultHeaders ?? {};

  /// Make a GET request
  Future<Map<String, dynamic>> get(
    String path, {
    Map<String, String>? queryParams,
  }) async {
    var url = Uri.parse('\$baseUrl\$path');

    if (queryParams != null && queryParams.isNotEmpty) {
      url = url.replace(queryParameters: queryParams);
    }

    final headers = {..._defaultHeaders};
    final response = await _client.get(url, headers: headers);

    if (response.statusCode >= 200 && response.statusCode < 300) {
      return jsonDecode(response.body) as Map<String, dynamic>;
    } else {
      throw RivetClientException(response.statusCode, response.body);
    }
  }

  /// Make a POST request
  Future<Map<String, dynamic>> post(
    String path, {
    Map<String, dynamic>? body,
  }) async {
    final url = Uri.parse('\$baseUrl\$path');
    final headers = {..._defaultHeaders, 'Content-Type': 'application/json'};

    final response = await _client.post(
      url,
      headers: headers,
      body: body != null ? jsonEncode(body) : null,
    );

    if (response.statusCode >= 200 && response.statusCode < 300) {
      return jsonDecode(response.body) as Map<String, dynamic>;
    } else {
      throw RivetClientException(response.statusCode, response.body);
    }
  }

  /// Make a PUT request
  Future<Map<String, dynamic>> put(
    String path, {
    Map<String, dynamic>? body,
  }) async {
    final url = Uri.parse('\$baseUrl\$path');
    final headers = {..._defaultHeaders, 'Content-Type': 'application/json'};

    final response = await _client.put(
      url,
      headers: headers,
      body: body != null ? jsonEncode(body) : null,
    );

    if (response.statusCode >= 200 && response.statusCode < 300) {
      return jsonDecode(response.body) as Map<String, dynamic>;
    } else {
      throw RivetClientException(response.statusCode, response.body);
    }
  }

  /// Make a DELETE request
  Future<void> delete(String path) async {
    final url = Uri.parse('\$baseUrl\$path');
    final headers = {..._defaultHeaders};

    final response = await _client.delete(url, headers: headers);

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw RivetClientException(response.statusCode, response.body);
    }
  }

  /// Close the HTTP client
  void close() {
    _client.close();
  }
}

/// Exception thrown when an API request fails
class RivetClientException implements Exception {
  final int statusCode;
  final String body;

  RivetClientException(this.statusCode, this.body);

  @override
  String toString() => 'RivetClientException(\$statusCode): \$body';
}
