import 'metadata.dart';
import 'type_analyzer.dart';

/// Generates type-safe Dart client code from controller metadata
class DartClientGenerator {
  final List<ControllerMetadata> controllers;
  final String className;
  final String baseUrl;
  final bool includeRiverpod;
  final TypeAnalyzer _typeAnalyzer = TypeAnalyzer();

  DartClientGenerator({
    required this.controllers,
    this.className = 'ApiClient',
    this.baseUrl = 'http://localhost:3000',
    this.includeRiverpod = false,
  });

  /// Generate complete client code
  String generate() {
    final buffer = StringBuffer();
    
    // Header
    buffer.writeln(_generateHeader());
    buffer.writeln();
    
    // Imports
    buffer.writeln(_generateImports());
    buffer.writeln();
    
    // Client class
    buffer.writeln(_generateClientClass());
    buffer.writeln();
    
    // Exception class
    buffer.writeln(_generateExceptionClass());
    
    // Riverpod providers if requested
    if (includeRiverpod) {
      buffer.writeln();
      buffer.writeln(_generateRiverpodProviders());
    }
    
    return buffer.toString();
  }

  String _generateHeader() {
    return '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Rivet Client Generator
// Generated at: ${DateTime.now().toIso8601String()}''';
  }

  String _generateImports() {
    final buffer = StringBuffer();
    buffer.writeln("import 'package:http/http.dart' as http;");
    buffer.writeln("import 'dart:convert';");
    
    if (includeRiverpod) {
      buffer.writeln("import 'package:flutter_riverpod/flutter_riverpod.dart';");
    }
    
    return buffer.toString();
  }

  String _generateClientClass() {
    final buffer = StringBuffer();
    
    buffer.writeln('class $className {');
    buffer.writeln('  final String baseUrl;');
    buffer.writeln('  final http.Client _client;');
    buffer.writeln('  String? _authToken;');
    buffer.writeln();
    
    // Constructor
    buffer.writeln('  $className({');
    buffer.writeln("    this.baseUrl = '$baseUrl',");
    buffer.writeln('    http.Client? client,');
    buffer.writeln('  }) : _client = client ?? http.Client();');
    buffer.writeln();
    
    // Auth token setter
    buffer.writeln('  void setAuthToken(String? token) {');
    buffer.writeln('    _authToken = token;');
    buffer.writeln('  }');
    buffer.writeln();
    
    // Generate methods for all routes
    for (final controller in controllers) {
      for (final route in controller.routes) {
        buffer.writeln(_generateMethod(route));
        buffer.writeln();
      }
    }
    
    // Helper methods
    buffer.writeln(_generateHelperMethods());
    
    buffer.writeln('}');
    
    return buffer.toString();
  }

  String _generateMethod(RouteMetadata route) {
    final buffer = StringBuffer();
    
    // Method signature
    final returnType = route.returnType?.displayName ?? 'dynamic';
    final methodName = _toCamelCase(route.functionName);
    
    buffer.writeln('  /// ${route.method} ${route.path}');
    if (route.requiresAuth) {
      buffer.writeln('  /// Requires authentication');
    }
    if (route.requiredRoles.isNotEmpty) {
      buffer.writeln('  /// Required roles: ${route.requiredRoles.join(", ")}');
    }
    
    buffer.write('  Future<$returnType> $methodName(');
    
    // Parameters
    final params = <String>[];
    for (final param in route.parameters) {
      if (param.isPathParam) {
        params.add('${param.type.displayName} ${param.name}');
      }
    }
    
    // Add body parameters for POST/PUT/PATCH
    if (['POST', 'PUT', 'PATCH'].contains(route.method)) {
      params.add('Map<String, dynamic> body');
    }
    
    buffer.write(params.join(', '));
    buffer.writeln(') async {');
    
    // Build URL
    buffer.write('    final url = Uri.parse');
    if (route.pathParameters.isEmpty) {
      buffer.writeln("('\$baseUrl${route.path}');");
    } else {
      buffer.writeln("('\$baseUrl${route.interpolatedPath}');");
    }
    
    // Make HTTP request
    buffer.writeln();
    buffer.write('    final response = await _client.${route.method.toLowerCase()}(');
    buffer.writeln('url,');
    buffer.writeln('      headers: _buildHeaders(');
    
    if (['POST', 'PUT', 'PATCH'].contains(route.method)) {
      buffer.writeln('        includeContentType: true,');
    }
    buffer.writeln('      ),');
    
    if (['POST', 'PUT', 'PATCH'].contains(route.method)) {
      buffer.writeln('      body: json.encode(body),');
    }
    
    buffer.writeln('    );');
    buffer.writeln();
    
    // Handle response
    buffer.writeln('    if (response.statusCode >= 200 && response.statusCode < 300) {');
    
    if (route.returnType != null && !route.returnType!.isSimple) {
      final deserializer = _typeAnalyzer.generateDeserializer(
        route.returnType!,
        'json.decode(response.body)',
      );
      buffer.writeln('      return $deserializer;');
    } else if (route.returnType != null) {
      buffer.writeln('      return json.decode(response.body);');
    } else {
      buffer.writeln('      return;');
    }
    
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln('    throw ApiException(response.statusCode, response.body);');
    buffer.writeln('  }');
    
    return buffer.toString();
  }

  String _generateHelperMethods() {
    return '''
  Map<String, String> _buildHeaders({bool includeContentType = false}) {
    final headers = <String, String>{};
    
    if (_authToken != null) {
      headers['Authorization'] = 'Bearer \$_authToken';
    }
    
    if (includeContentType) {
      headers['Content-Type'] = 'application/json';
    }
    
    return headers;
  }
  
  void dispose() {
    _client.close();
  }''';
  }

  String _generateExceptionClass() {
    return '''
class ApiException implements Exception {
  final int statusCode;
  final String message;
  
  ApiException(this.statusCode, this.message);
  
  @override
  String toString() => 'ApiException(\$statusCode): \$message';
}''';
  }

  String _generateRiverpodProviders() {
    final buffer = StringBuffer();
    
    buffer.writeln('// ============================================');
    buffer.writeln('// Riverpod Providers');
    buffer.writeln('// ============================================');
    buffer.writeln();
    
    // Client provider
    // Using simple Provider for the client
    buffer.writeln('final ${_toLowerCamelCase(className)}Provider = Provider<$className>((ref) {');
    buffer.writeln("  return $className(baseUrl: '$baseUrl');");
    buffer.writeln('});');
    buffer.writeln();
    
    // Generate providers for GET routes
    for (final controller in controllers) {
      for (final route in controller.routes) {
        if (route.method == 'GET' && route.pathParameters.isEmpty) {
          final providerName = '${_toLowerCamelCase(route.functionName)}Provider';
          final returnType = route.returnType?.displayName ?? 'dynamic';
          
          buffer.writeln('final $providerName = FutureProvider<$returnType>((ref) async {');
          buffer.writeln('  final client = ref.watch(${_toLowerCamelCase(className)}Provider);');
          buffer.writeln('  return client.${_toCamelCase(route.functionName)}();');
          buffer.writeln('});');
          buffer.writeln();
        }
      }
    }
    
    return buffer.toString();
  }

  String _toCamelCase(String input) {
    if (input.isEmpty) return input;
    return input[0].toLowerCase() + input.substring(1);
  }

  String _toLowerCamelCase(String input) {
    return input.replaceAllMapped(
      RegExp(r'[A-Z]'),
      (match) => match.group(0)!.toLowerCase(),
    );
  }
}
