/// Generates Dart model classes from type definitions
library;

import 'models.dart';

/// Generates Dart model classes with JSON serialization
class ModelGenerator {
  /// Generate a complete Dart class from a type definition
  String generate(TypeDefinition type) {
    final buffer = StringBuffer();

    // Class declaration
    buffer.writeln('class ${type.name} {');

    // Fields
    type.fields.forEach((name, field) {
      buffer.writeln('  final ${field.fullType} $name;');
    });

    buffer.writeln();

    // Constructor
    buffer.write('  ${type.name}({');
    final requiredFields = type.fields.entries
        .where((e) => !e.value.isNullable)
        .map((e) => 'required this.${e.key}');
    final optionalFields = type.fields.entries
        .where((e) => e.value.isNullable)
        .map((e) => 'this.${e.key}');

    buffer.write(requiredFields.join(', '));
    if (requiredFields.isNotEmpty && optionalFields.isNotEmpty) {
      buffer.write(', ');
    }
    buffer.write(optionalFields.join(', '));
    buffer.writeln('});');

    buffer.writeln();

    // fromJson factory
    buffer.writeln(
      '  factory ${type.name}.fromJson(Map<String, dynamic> json) {',
    );
    buffer.writeln('    return ${type.name}(');

    type.fields.forEach((name, field) {
      if (field.isList) {
        if (field.dartType == 'dynamic') {
          buffer.writeln('      $name: json[\'$name\'] as List<dynamic>,');
        } else if (_isPrimitive(field.dartType)) {
          buffer.writeln(
            '      $name: (json[\'$name\'] as List<dynamic>).cast<${field.dartType}>(),',
          );
        } else {
          buffer.writeln(
            '      $name: (json[\'$name\'] as List<dynamic>).map((e) => ${field.dartType}.fromJson(e as Map<String, dynamic>)).toList(),',
          );
        }
      } else if (_isPrimitive(field.dartType)) {
        if (field.isNullable) {
          buffer.writeln('      $name: json[\'$name\'] as ${field.dartType}?,');
        } else {
          buffer.writeln('      $name: json[\'$name\'] as ${field.dartType},');
        }
      } else {
        // Custom type
        if (field.isNullable) {
          buffer.writeln(
            '      $name: json[\'$name\'] != null ? ${field.dartType}.fromJson(json[\'$name\'] as Map<String, dynamic>) : null,',
          );
        } else {
          buffer.writeln(
            '      $name: ${field.dartType}.fromJson(json[\'$name\'] as Map<String, dynamic>),',
          );
        }
      }
    });

    buffer.writeln('    );');
    buffer.writeln('  }');

    buffer.writeln();

    // toJson method
    buffer.writeln('  Map<String, dynamic> toJson() {');
    buffer.writeln('    return {');

    type.fields.forEach((name, field) {
      if (field.isList && !_isPrimitive(field.dartType)) {
        buffer.writeln(
          '      \'$name\': $name.map((e) => e.toJson()).toList(),',
        );
      } else if (!_isPrimitive(field.dartType) && !field.isNullable) {
        buffer.writeln('      \'$name\': $name.toJson(),');
      } else if (!_isPrimitive(field.dartType) && field.isNullable) {
        buffer.writeln('      \'$name\': $name?.toJson(),');
      } else {
        buffer.writeln('      \'$name\': $name,');
      }
    });

    buffer.writeln('    };');
    buffer.writeln('  }');

    buffer.writeln('}');

    return buffer.toString();
  }

  /// Generate all models
  String generateAll(List<TypeDefinition> types) {
    final buffer = StringBuffer();

    buffer.writeln('// AUTO-GENERATED CODE - DO NOT EDIT');
    buffer.writeln('// Generated by Rivet Code Generator');
    buffer.writeln();

    for (final type in types) {
      buffer.writeln(generate(type));
      buffer.writeln();
    }

    return buffer.toString();
  }

  bool _isPrimitive(String type) {
    return ['String', 'int', 'double', 'bool', 'dynamic'].contains(type);
  }
}
